### ISSUE TITLE
Connection aborted: Name or service not known error

### ISSUE THREAD

**Issue by siddharthasahu** [mk-fg/python-onedrive#59]
Hi,

After successfully executing `onedrive-cli auth`, I'm getting this error:

% onedrive-cli quota
Traceback (most recent call last):
  File "/usr/bin/onedrive-cli", line 9, in <module>
    load_entry_point('python-onedrive==15.5.6', 'console_scripts', 'onedrive-cli')()
  File "/usr/lib/python2.7/site-packages/onedrive/cli_tool.py", line 301, in main
    df, ds = map(size_units, api.get_quota())
  File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 646, in get_quota
    return op.itemgetter('available', 'quota')(super(OneDriveAPI, self).get_quota())
  File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 378, in get_quota
    return self('me/skydrive/quota')
  File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 367, in __call__
    try: return self.request(api_url(), **kwz)
  File "/usr/lib/python2.7/site-packages/onedrive/api_v5.py", line 189, in request
    raise raise_for.get(code, ProtocolError)(code, message)
onedrive.api_v5.ProtocolError: (None, "('Connection aborted.', gaierror(-2, 'Name or service not known')) [type: <class 'requests.exceptions.ConnectionError'>, repr: ConnectionError(ProtocolError('Connection aborted.', gaierror(-2, 'Name or service not known')),)]")

**Comment by siddharthasahu** [comment]
Nvm. Seems to be a local network issue.
